name: Manual event starter
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check OS is Linux
        run: echo "The OS on the runner is $RUNNER_OS"
      - name: step_one
        run: echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: step_two
        run: printf '%s\n' "action state is $action_state"
