name: Share data between jobs
on: workflow_dispatch

jobs:
  job_1:
    name: Upload file
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello world" > file.txt
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: file.txt
        path: .

  job_2:
    name: Download file
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - uses: actions/download-artifact@v4.3.0
      with:
        path: .
    - run: cat file.txt
